// All 56 Montana counties — the Cadastral layer covers the whole state, so this is
// every CountyName value the live API actually returns (verified via a groupBy/count
// query against the layer on 2026-08-14, not guessed/typed by hand — county naming has
// gotchas, e.g. "Lewis and Clark" not "Lewis & Clark", which returns zero rows).
//
// Lives in its own module (not runAll.js, where it originally was) so other ingestion
// modules — e.g. fredMarketData.js — can import it without creating a circular
// dependency with runAll.js, which now imports from those modules too.
export const TARGET_COUNTIES = [
  "Beaverhead",
  "Big Horn",
  "Blaine",
  "Broadwater",
  "Carbon",
  "Carter",
  "Cascade",
  "Chouteau",
  "Custer",
  "Daniels",
  "Dawson",
  "Deer Lodge",
  "Fallon",
  "Fergus",
  "Flathead",
  "Gallatin",
  "Garfield",
  "Glacier",
  "Golden Valley",
  "Granite",
  "Hill",
  "Jefferson",
  "Judith Basin",
  "Lake",
  "Lewis and Clark",
  "Liberty",
  "Lincoln",
  "Madison",
  "McCone",
  "Meagher",
  "Mineral",
  "Missoula",
  "Musselshell",
  "Park",
  "Petroleum",
  "Phillips",
  "Pondera",
  "Powder River",
  "Powell",
  "Prairie",
  "Ravalli",
  "Richland",
  "Roosevelt",
  "Rosebud",
  "Sanders",
  "Sheridan",
  "Silver Bow",
  "Stillwater",
  "Sweet Grass",
  "Teton",
  "Toole",
  "Treasure",
  "Valley",
  "Wheatland",
  "Wibaux",
  "Yellowstone",
];
